### ISSUE TITLE
Running Sharpfuzz for .net framework

### ISSUE THREAD

**Issue by jnyrup** [Metalnem/sharpfuzz#15]
I'm trying to run Sharpfuzz on .net framework assemblies, but so far without any luck.

The Usage section on the front page says it should be doable for net45 (As far as I read it).

When compiling my net47 project using mono and running 
```
afl-fuzz -i testcases/ -o output/ ConsoleAppMono/bin/x64/Debug/ConsoleAppMono.exe
```

I get the following error 
```
[-] PROGRAM ABORT : Program 'ConsoleAppMono/bin/x64/Debug/ConsoleAppMono.exe' is not an ELF binary
         Location : check_binary(), src/afl-fuzz-init.c:1891
```

Do you have any pointers on how to do this, or have I misunderstood it being possible for .net framework assemblies?

**Comment by Metalnem** [comment]
I've just tried fuzzing .NET framework application built with mono, and it's working for me.

Instead of doing this:

```shell
afl-fuzz -i testcases/ -o output/ ConsoleAppMono/bin/x64/Debug/ConsoleAppMono.exe
```

You should be doing this:

```shell
afl-fuzz -i testcases/ -o output/ mono ConsoleAppMono/bin/x64/Debug/ConsoleAppMono.exe
```

In addition to that, make sure you follow the steps from the **Installation** section of the README file (either run the installation script to disable instrumentation check, or set the **AFL_SKIP_BIN_CHECK** env variable).

**Comment by jnyrup** [comment]
That worked, thanks!
