### ISSUE TITLE
Mixed mode assemblies

### ISSUE THREAD

**Issue by danmosemsft** [Metalnem/sharpfuzz#3]
Hello, I see you [block them](https://github.com/Metalnem/sharpfuzz/commit/f10b3f3d88e1e781b5582324d67501441630c437#diff-474b19efb8197bee9b8634563dfb0747). Is this perhaps due to a hard limitation in Cecil?

I would like to instrument System.Private.Corelib. Is there any workaround you know of? 

@rmkerr

**Comment by danmosemsft** [comment]
I see that the code [special cases ](https://github.com/Metalnem/sharpfuzz/blob/7c4412b300269db82e47e9a1a019b7a4a83a6488/src/SharpFuzz/Fuzzer.cs#L57) S.P.Corelib further down, and it's mentioned in the help output also. So perhaps I'm missing something.

```
dan@danmose3:~/fuzz/1/bin/Debug/netcoreapp3.0/linux-x64/publish$ sharpfuzz System.Private.CoreLib.dll System.String
Cannot instrument mixed-mode assemblies.
```

**Comment by danmosemsft** [comment]
I tried rebuilding sharpfuzz with that check removed, and with the write changed:
```c#
-                       src.Write(dst);
+                       if (src.IsILOnly)
+                       {
+                           src.Write(dst);
+                       }
+                       else
+                       {
+                           src.NativeWrite(dst);
+                       }
```
as suggested in the dnlib [README](https://github.com/0xd4d/dnlib/blob/8cedb9b020fa577deb0af6e72ccd778c2f91d795/README.md)

However that fails differently:
```
dan@danmose3:~/fuzz/1/bin/Debug/netcoreapp3.0/linux-x64$ dotnet exec ~/git/sharpfuzz/src/SharpFuzz.CommandLine/bin/Debug/netcoreapp2.1/linux-x64/publish/SharpFuzz.CommandLine.dll System.Runtime.dll
Failed to instrument the specified file, most likely because it's not a valid .NET assembly.
dnlib.DotNet.Writer.ModuleWriterException: Could not create header
   at dnlib.DotNet.Writer.NativeModuleWriter.CreateHeaderSection(IChunk& extraHeaderData)
   at dnlib.DotNet.Writer.NativeModuleWriter.WriteFile()
   at dnlib.DotNet.Writer.NativeModuleWriter.WriteImpl()
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest)
   at SharpFuzz.Fuzzer.Instrument(ModuleDefMD src, Stream dst, Func`2 matcher, TypeDef traceType) in /home/dan/git/sharpfuzz/src/SharpFuzz/Fuzzer.cs:line 117
   at SharpFuzz.Fuzzer.Instrument(String source, Func`2 matcher) in /home/dan/git/sharpfuzz/src/SharpFuzz/Fuzzer.cs:line 63
   at SharpFuzz.CommandLine.Program.Main(String[] args) in /home/dan/git/sharpfuzz/src/SharpFuzz.CommandLine/Program.cs:line 51
```

**Comment by Metalnem** [comment]
All .NET Core implementation assemblies are mixed mode, which is why you are getting that error. Mono.Cecil couldn't handle them, which is why I switched to dnlib. But dnlib gave me the exact same error you just encountered. That's why I developed a different approach for fuzzing .NET Core assemblies:

1) For fuzzing classes outside of System.Private.CoreLib, I'm using the MyGet feed, where assemblies are IL only. You can find my setup [here](https://github.com/Metalnem/sharpfuzz-samples/tree/master/CoreFX).

2) For fuzzing classes in the System.Private.CoreLib, I'm using a custom CoreCLR build, where I skip generating the native images by using the skipcrossgen flag. Again, you can find my complete setup [here](https://github.com/Metalnem/sharpfuzz-samples/tree/master/System.Private.CoreLib). One important thing here is that you have to specify classes or namespaces that you want to instrument (first reason is that not everything in the CoreLib can be instrumented without breaking your program, and the second one is that instrumenting too many classes would give you a lot of noise).

If you have any additional questions, I'll be glad to assist you (I also plan to write more detailed instructions in the README file).

**Comment by Metalnem** [comment]
By the way, the [CoreFX](https://github.com/Metalnem/sharpfuzz-samples/tree/master/CoreFX) fuzzing project I referenced in the previous comment is currently working only with .NET Core 2.2. I will try to update it in the following days to work with .NET Core 3.0, but you can do it yourself in the meantime by switching the target framework and also updating the **Microsoft.Private.CoreFx.NETCoreApp** version. You will also have to use the daily build of .NET Core 3.0 because of dotnet/corefx#35555.

**Comment by danmosemsft** [comment]
@Metalnem thanks, good to know it wasn't my mistake. Of course - I should eliminate crossgen.

**Comment by Metalnem** [comment]
Here you go: [Fuzzing .NET Core](https://github.com/Metalnem/sharpfuzz/blob/master/docs/fuzzing-dotnet-core.md).

**Comment by danmosemsft** [comment]
Thanks!
